### ISSUE TITLE
Time period options

### ISSUE THREAD

**Issue by channsoden** [ucb-rit/savio-queue-helper#1]
I noticed that if you run sq when you don't have any running/pending jobs it gives you the summary of recent jobs. This is really handy and the layout & colorization is superior to basic squeue. Could you include an option/s to force this type of output? For example, it would be helpful to see only currently running/pending jobs, recent jobs including running and finished jobs, and recently finished jobs. For bonus points it could be possible to set the time window, either in the form of T+X days from present or as a date interval.

**Comment by nicolaschan** [comment]
Thanks for the suggestion! I've added it as:
```bash
sq -a -S 2020-10-09
```
The `-a` means show all jobs (current and past), and `-S` is the start time to filter from. The argument to `-S` is whatever format `sacct` takes.
